### ISSUE TITLE
Debug Bodymovin Extension Crash during Export w/ Expressions

### ISSUE THREAD

**Issue by njho** [bodymovin/bodymovin-extension#112]
It appears that bodymovin will crash with `render failed` randomly during our export.

**Comment by njho** [comment]
It appears that we're able to debug the extension using: 

`chrome://inspect/#devices`

And configuring the port addresses with the following
![image](https://user-images.githubusercontent.com/16584869/151674750-c1853533-b74c-45ee-920e-e403a3a51df5.png)

There I can verify that the reason it is failing is due to a broken `else` statement as  it states it inside of the `console`.

![image](https://user-images.githubusercontent.com/16584869/151674990-90616f6e-3229-42d5-bba4-71deb4890807.png)

Bodymovin uses `Esprima.js` in order to parse the expressions, and if there is a syntax error, it may crash.

**Comment by bodymovin** [comment]
@njho if you find the expression that crashes it, it'd be great to share, so I can fix it, or at least catch the error.
