### ISSUE TITLE
Export using a script

### ISSUE THREAD

**Issue by Bjorninn1** [bodymovin/bodymovin-extension#126]
Hello, I use Bodymovin a lot and was thinking if it is possible to export a lottie file from AE automatically somehow without using the Bodymovin UI buttons.

Do you know if there is a way to do this either by accessing bodymovin through code or with some other method? Would really appreciate if someone could point me in the right direction.

Thank you.

**Comment by bodymovin** [comment]
hi, are you looking to run bodymovin from another extension?

**Comment by Bjorninn1** [comment]
I was thinking about an AE script written in Javascript or just any other possible method of doing this without manually exporting each Lottie file.

**Comment by bodymovin** [comment]
not sure I completely follow, but if you build your own CEP panel and bodymovin is running, you could call its methods to run it

**Comment by Bjorninn1** [comment]
Great thanks, where can I see the available Bodymovin methods? is this documented somewhere?

**Comment by bodymovin** [comment]
unfortunately there is not, since it hasn't been developed as a public API, but this is the method that is called to render a composition:
https://github.com/bodymovin/bodymovin-extension/blob/master/bundle/jsx/compsManager.jsx#L192
and here's how the bodymovin CEP panel uses it
https://github.com/bodymovin/bodymovin-extension/blob/master/src/helpers/CompositionsProvider.js#L363

**Comment by Bjorninn1** [comment]
Ok how about setting options for each render? similar to the options set in the ui

**Comment by bodymovin** [comment]
yes, you should pass a similar config like the one the bodymovin panel submits.
as a starting point these are the default settings each composition provides to the render
https://github.com/bodymovin/bodymovin-extension/blob/master/src/redux/reducers/compositions.js#L29

**Comment by Bjorninn1** [comment]
Great! Thank you very much for this info. I will look further into this.
