### ISSUE TITLE
Include in json export not working

### ISSUE THREAD

**Issue by amandalui** [bodymovin/bodymovin-extension#34]
Hey! I've really enjoyed using this plugin over the past few years, it's been a great way to include animations in projects.

Recently came across something that seems like a bug. When exporting compositions with images the option to include assets in the json file used to convert the image to json. This was working a few days ago but now no longer works. Instead, it links to an external image instead of converting it.

Thoughts?

**Comment by bodymovin** [comment]
Hi, what version are you using?
Also, can you share a small screen capture of how you are exporting?

**Comment by amandalui** [comment]
AE cc 2019

![image](https://user-images.githubusercontent.com/25451171/72590241-2556c880-38b2-11ea-8c89-4390dd8f983c.png)

**Comment by bodymovin** [comment]
hmm can you share the .aep?

**Comment by amandalui** [comment]
I restarted after effects and that seems to have done the trick. thanks!
