### ISSUE TITLE
Bodymovin stuck on exporting sequence

### ISSUE THREAD

**Issue by tomdekr** [bodymovin/bodymovin-extension#35]
Hi there I made an C4D sequence and tried exporting it with Bodymovin in AE 2019 as a Lottie JSON.. but it repeatedly gets stuck around frame 120 of 244.  Does anyone know how to fix this? (My first time using bodymovin and it hasn't worked yet)  
<img width="1620" alt="bodymovin not working" src="https://user-images.githubusercontent.com/16013318/73676550-dd5ae280-46b4-11ea-8ae4-1dda8d456272.png">

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by tomdekr** [comment]
Ofcourse! 
[tomdekr-banner-aep.zip](https://github.com/bodymovin/bodymovin-extension/files/4152623/tomdekr-banner-aep.zip)

**Comment by tomdekr** [comment]
> Hi, can you share the .aep?
Hi, I've tried different image formats, different bodymovin installs (current version 5.6.3).. still not working.

.aep only:
[tomdekr-banner-aep.zip](https://github.com/bodymovin/bodymovin-extension/files/4155732/tomdekr-banner-aep.zip)
with png sequence:
https://we.tl/t-nG4Lg0C9qD

**Comment by bodymovin** [comment]
Hi, I just tried it and it exported correctly.
Do you have any special setup in the assets settings of the bodymovin panel?

**Comment by tomdekr** [comment]
Only thing I've changed besides standard render settings  is checking the "include in Json" option.

**Comment by bodymovin** [comment]
I've been able to reproduce it. Very strange.
I'm looking into it.

**Comment by tomdekr** [comment]
Any luck :)?

**Comment by bodymovin** [comment]
Still working on it

**Comment by bodymovin** [comment]
ok, got a fix.
Will be available on the next release.

**Comment by bodymovin** [comment]
Done!
Should be fixed on version 5.6.4
Feel free to reopen if you have any issues.
