### ISSUE TITLE
Unable to execute scripts at line 226

### ISSUE THREAD

**Issue by joshderosa** [bodymovin/bodymovin-extension#4]
@bodymovin I've been getting an error in bodymovin and I can't seem to resolve it.

Unable to execute script at line 226. After Effects error: Error in output for render queue item3; output module 1. Directory does not exist: 

https://www.dropbox.com/s/vtuvc35lixds78y/Screen%20Shot%202018-07-26%20at%2011.29.36%20AM.png?dl=0

**Comment by bodymovin** [comment]
Hi, what version of AE are you using?
Do you know what is that folder pointing to?

**Comment by joshderosa** [comment]
@bodymovin I moved all the attributes into a new project and it solved the issue. I'm not sure why it kept complaining about that folder. None of the assets were located in that folder. Anyways, I think I have it fixed. Thanks for your time, and for developing bodymovin!!
