### ISSUE TITLE
Bodymovin renders animation but nothing shows when viewed - Update: resolved, but animation has lag

### ISSUE THREAD

**Issue by RayKay91** [bodymovin/bodymovin-extension#42]
Hello,

I made a generate stroke path to animate a reveal of some text. when rendering in Bodymovin it completes the render and outputs the JSON file but nothing shows when I try to use it or preview it on http://lottiefiles.com/preview .

I have included a mov file of how I'd like it to look, the AEP file and the JSON file outputted by Bodymovin

Thanks for your help, and for creating such a great plugin!

Update: Managed to get it to work by converting text to vector shape by right clicking > create > convert to vector shape. However there is lag towards the end of the animation.

[animation attempt.zip](https://github.com/bodymovin/bodymovin-extension/files/4332927/animation.attempt.zip)

**Comment by bodymovin** [comment]
Hi, I don't have that font installed and I'm having trouble finding a replacement. can you provide another example with a free font to download?

**Comment by RayKay91** [comment]
Hi!

The font can be downloaded for free here

https://arabicfonts.net/fonts/jf-flat-regular

The other weights require payment but I use this regular font size. 

Thanks for looking into this!

**Comment by bodymovin** [comment]
Stroke effect has very poor support, have you tried using an alpha mask with shape layer using a stroke with trim path?
