### ISSUE TITLE
After Effect 2015 Blank Panel

### ISSUE THREAD

**Issue by namikos** [bodymovin/bodymovin-extension#46]
Hello,

I want to use bodymovin but, when I go on "windows>extensions>bodymovin" a blank panel is opening. After resizing and waiting nothing happens.

- I installed it with an zxp installer.
- I also added the "playerdebugmode" registrykey.

Can anyone help me out?

![image](https://user-images.githubusercontent.com/36844140/80865728-949ecf80-8c8b-11ea-9a69-1a4b69a03b93.png)

**Comment by bodymovin** [comment]
hi, there is a problem with the latest plugin and older versions of AE. Can you try upgrading AE or installing an older version of the plugin?

**Comment by namikos** [comment]
Thanks. I installed a newer version of ae and now its working
