### ISSUE TITLE
Issue with exporting AE animation

### ISSUE THREAD

**Issue by volcaer** [bodymovin/bodymovin-extension#5]
I keep trying to export the Serving Platter Comp or Serving Platter Animation, and the animation continuously renders as blank. I checked the supported features and everything I'm doing in the animation is supported, so I'm not entirely sure what's going on. I'm not too familiar with coding, etc. so I'm not sure if I'm missing something. Below I've attached my AEP file and the exported JSON for the Serving Platter.

[Copia Connect - Icon Animations.aep.zip](https://github.com/bodymovin/bodymovin-extension/files/2466856/Copia.Connect.-.Icon.Animations.aep.zip)

[data.json.zip](https://github.com/bodymovin/bodymovin-extension/files/2466857/data.json.zip)

**Comment by bodymovin** [comment]
Hi, negative layer stretching is not supported yet.
You can try using time remapping instead by precomposing the layer, or reworking the layers in the original direction.

**Comment by volcaer** [comment]
Thank you! I'll try it out. :)
