### ISSUE TITLE
B&W Gradient problems - not related to AE Language

### ISSUE THREAD

**Issue by woozygoozy** [bodymovin/bodymovin-extension#56]
I have a problem trying to export a gradient layer where the gradient turns out to be black and white and lacking all transparency... My AE installation is in english so I don't know what to event try to fix it....

Here is the AEP 
[money.aep.zip](https://github.com/bodymovin/bodymovin-extension/files/5212910/money.aep.zip)

Please help!

**Comment by bodymovin** [comment]
Hi, can you try saving the project before exporting?

**Comment by woozygoozy** [comment]
I did... i have tried everything that I could find that was suggested - I renamed the gradient layers with _ instead of spaces (including the gradient fill_1 and others)

**Comment by bodymovin** [comment]
Can you specify what layer and property is a gradient or share a simplified example?

**Comment by woozygoozy** [comment]
sorry do the delay... its the layer called glint with alpha matte

**Comment by woozygoozy** [comment]
also I am having the following issue - so i am rendering out the animation (no gradient) in AE it seems all in order and opacity is set to 100% at the end of the animated sequence. But the json renders with the text having different color and/or transparency - can't figure out why... here is the json and the AEP 
[Archive.zip](https://github.com/bodymovin/bodymovin-extension/files/5214809/Archive.zip)

**Comment by bodymovin** [comment]
the first project you shared doesn't have any layer with that name. Can you check it again?

**Comment by woozygoozy** [comment]
Apologies the first project I sent was the wrong one...  I attach it again for avoidance of doubt.... 
[Archive 2.zip](https://github.com/bodymovin/bodymovin-extension/files/5219189/Archive.2.zip)

The comp money v2 - shows the issue with the gradient
The comp money v3 - has the issue with transparency (its not apparent in the AEP but the json exported (attached) shows the problem)

Thanks again for looking at it!

**Comment by woozygoozy** [comment]
Any thoughts?

**Comment by bodymovin** [comment]
Hi, I don't see any of those issues when exporting. Perhaps I'm not noticing them.
Can you share a link with your animation implemented?

**Comment by coderwj** [comment]
Hi, I meet the same problem. And I find that the gradient color data exported by Bodymovin, is 1 or 0, not the correct 0.xxx color.
The exported data.json:
![error1](https://user-images.githubusercontent.com/15345564/96605863-4066d500-1329-11eb-9582-a20874bbfe55.png)
The Gradient Color Fill attributes in AE:
![image](https://user-images.githubusercontent.com/15345564/96606384-cc78fc80-1329-11eb-8dc2-aed41a26aa2f.png)

My working space is Mac OS 10.15.7. AE is 2020(17.0.5) Chinese version.

**Comment by bodymovin** [comment]
@coderwj it looks like your AE is on another language. 
Perhaps this issue can help solve it.
https://github.com/airbnb/lottie-web/issues/1201

**Comment by coderwj** [comment]
> @coderwj it looks like your AE is on another language.
> Perhaps this issue can help solve it.
> [airbnb/lottie-web#1201](https://github.com/airbnb/lottie-web/issues/1201)

Tanks, it really solve my problem.
