### ISSUE TITLE
Update bodymovin extension in the Creative Cloud / Adobe Exchange

### ISSUE THREAD

**Issue by JannikGM** [bodymovin/bodymovin-extension#59]
While trying to resolve #57 I tried to upgrade my bodymovin extension, but [the Creative Cloud / Adobe Exchange is stuck on 5.7.1](https://exchange.adobe.com/creativecloud.details.12557.html) (April 2019).

The [latest version mentioned in git at the time of writing is 5.7.3](https://github.com/bodymovin/bodymovin-extension/commit/29c63cdc53f46b0552a6c66978d5c5e009c779f2) (September 2020; but I'm not sure if it's considered "released" yet).

I'm not sure about the changes in 5.7.2 and 5.7.3 but it would probably be good to have these changes in Adobe Exchange.

**Comment by bodymovin** [comment]
I've pushed a new version and it should be approved next week.
