### ISSUE TITLE
Second layer (reversed keyframes) not showing up when exporting?

### ISSUE THREAD

**Issue by sassmira** [bodymovin/bodymovin-extension#67]
Hi! I seem to be having an issue with the second half of my animation exporting properly through bodymovin
The first half works fine and looks great, but I had duplicated the layer and used time stretch to reverse the keyframes to reverse the movement of my character and it doesn't seem to pick up the second layer at all.
Still kinda new to this! Am I doing something wrong?
[photographer.aep.zip](https://github.com/bodymovin/bodymovin-extension/files/5823759/photographer.aep.zip)

Thank you!!

**Comment by bodymovin** [comment]
Hi, negative stretching of layers is not supported unfortunately. But if you convert the layer into a precomp and use time remapping, you can get the same effect and it should work fine.

**Comment by sassmira** [comment]
That worked!! thank you
