### ISSUE TITLE
Error with animation (skipping frames)

### ISSUE THREAD

**Issue by DDrago** [bodymovin/bodymovin-extension#7]
i am trying to export my animations as Lottie JSON files but with most compositions i have animation errors (skipping frames)
i am using the latest available version of bodymovin on aescripts which are `Bodymovin 5.4.2` on `After Effects version CC 2018`
please help me identify this issue, i've uploaded the lottie files exported and the Aep file.

[Lottie.zip](https://github.com/bodymovin/bodymovin-extension/files/2636118/Lottie.zip)
[Arabic words Composer (Lesson 5).zip](https://github.com/bodymovin/bodymovin-extension/files/2636119/Arabic.words.Composer.Lesson.5.zip)

Thanks for the amazing efforts

**Comment by bodymovin** [comment]
stroke effect has very limited support.
I'd suggest that you try using a regular mask for this type of effect.
Since you're not really using the alpha channel, It'll be much more performant than other types of masks.

**Comment by DDrago** [comment]
Thank you for replying and support, can you please elaborate more on what you mean by regular mask, is there anyway that i mustn't do all the work again?

**Comment by DDrago** [comment]
Thank you for you support that was helpful and fixed my problem
